export const ADD_PLAYLIST = 'ADD_PLAYLIST';
export const REMOVE_PLAYLIST = 'REMOVE_PLAYLIST';
export const PLAY_PLAYLIST_REQUEST = 'PLAY_PLAYLIST_REQUEST';
export const PAUSE_PLAYLIST_REQUEST = 'PAUSE_PLAYLIST_REQUEST';
export const PLAY_MASTER_PLAYLIST = 'PLAY_MASTER_PLAYLIST';
export const PAUSE_MASTER_PLAYLIST = 'PAUSE_MASTER_PLAYLIST';
